services:
  frontend-recommendation-app:
    image: darshanaswath/frontend-recommendation-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
