services:
  frontend-recommendation-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
